---
  openapi: "3.0.0"
  info: 
    title: "no_title"
    description: "no_description"
    version: "no_version"
  servers: 
    - 
      url: "http://localhost:3000"
  tags: 
    - 
      name: "info"
      description: "Main info about API"
    - 
      name: "health"
      description: "Everything about API's health"
    - 
      name: "env"
      description: "Setted ENV variables"
  components: 
    securitySchemes: 
      bearerToken: 
        type: "http"
        scheme: "bearer"
  paths: 
    /api/env: 
      get: 
        tags: 
          - "env"
        summary: "Returns the setted ENV variables"
        security: 
          - 
            bearerToken: []
        responses: 
          200: 
            description: "OK"
            content: 
              application/json: 
                schema: 
                  type: "object"
                  properties: 
                    API_NAME: 
                      type: "string"
                      example: "API"
                    API_PORT: 
                      type: "number"
                      example: 3000
          401: 
            description: "Unauthorized"
            content: 
              application/json: 
                schema: 
                  type: "object"
                  properties: 
                    message: 
                      type: "string"
                      example: "you are not allowed to access endpoint GET /api/env ..."
                    internal_code: 
                      type: "string"
                      example: "unauthorized"
    /api/health: 
      get: 
        tags: 
          - "health"
        summary: "Returns the health status of the API"
        responses: 
          200: 
            description: "OK"
            content: 
              application/json: 
                schema: 
                  type: "object"
                  properties: 
                    status: 
                      type: "string"
                      example: "DOWN"
    /api/info: 
      get: 
        tags: 
          - "info"
        summary: "Return the main info of the API"
        responses: 
          200: 
            description: "OK"
            content: 
              application/json: 
                schema: 
                  type: "object"
                  properties: 
                    version: 
                      type: "string"
                      example: "0.0.0"
                    author: 
                      type: "string"
                      example: "John Doe"
